Homework-5
mrosminin/go-core pull request #10
Opened 2020-11-01 22:56 UTC by mrosminin

двоичный поиск по документам в массиве заменен на использование двоичное дерева

2020-11-02 22:03 UTC, DmitriyVTitov requested changes
Замечания к архитектуре приложения не позволяют его принять.

2020-11-02 22:03 UTC, DmitriyVTitov commented on homework-5/pkg/engine/engine.go
> +}
и зачем нужна такая функция здесь, если всё делает `index`?

2020-11-02 22:03 UTC, DmitriyVTitov commented on homework-5/pkg/index/btree/btree.go
> +package btree
дерево должно хранить документы, а не индекс.

2020-11-02 22:03 UTC, DmitriyVTitov commented on homework-5/pkg/index/btree/btree.go
> +}
оно и хранит документы, тогда что оно делает в каталоге `index`?

2020-11-02 22:03 UTC, DmitriyVTitov commented on homework-5/pkg/index/index.go
> +func (s *Service) Find(str string) []crawler.Document {
индекс же не хранит документы. почему он их выдаёт?
задача индекса - хранить обратный индекс и искать номера документов, а не сами документы.

2020-11-03 16:12 UTC, mrosminin reviewed
SFTM

2020-11-03 16:30 UTC, closed without merging