Hw14
mrosminin/go-core pull request #25
Opened 2020-11-29 14:58 UTC by mrosminin

Нужно добавить в поисковик возможность принимать поисковые запросы с помощью telnet или специального клиента.
Удалить из поисковика артефакты из прошлых занятий: флаги командной строки, интерактивный режим(CLI), файлы и всё прочее, что не имеет отношения к текущему состоянию задачи.

Создать отдельный исполняемый пакет “netsrv”, который бы обеспечивал интерактивный режим работы с пользователем. 

Служба “netsrv” должна принимать соединения на порту 8000 на всех сетевых интерфейсах системы. 

Служба должна читать текстовые поисковые запросы и в ответ выдавать результаты поиска.

Разработать текстового клиента службы “netsrv”. Клиент должен работать в интерактивном режиме (запрос – ответ – запрос – и т.д.)

2020-11-30 18:41 UTC, mrosminin reviewed
ОК

2020-11-30 18:41 UTC, mrosminin commented on homework-14/cmd/client/main.go
> +	for {
цикл для переподлключения после срабатывания таймаута

2020-11-30 18:41 UTC, mrosminin commented on homework-14/cmd/server/main.go
> +		query = strings.Replace(query, "\n", "", -1)
надо очистить от символа новой строки
для мак достаточно \n убрать, не уверен насчет других ОС, потому наверняка

2020-11-30 18:41 UTC, mrosminin commented on homework-14/cmd/server/main.go
> +		jsonData, err := json.Marshal(docs)
поскольку передаем только одну строку, а вывод в клиенте хочется видеть форматированных, кодирую в json.

2020-12-05 00:12 UTC, DmitriyVTitov requested changes
Лучше читайте задание:

> Создать отдельный исполняемый пакет “netsrv”, который бы обеспечивал интерактивный режим работы с пользователем. 
> 
> Служба “netsrv” должна принимать соединения на порту 8000 на всех сетевых интерфейсах системы.

2020-12-05 00:12 UTC, DmitriyVTitov commented on homework-14/cmd/client/main.go
> +	for {
горе от ума.
таймаут нужен как раз для того, чтобы клиентов отключать.

2020-12-05 00:12 UTC, DmitriyVTitov commented on homework-14/cmd/client/main.go
> +
ПУСТАЯ СТРОКА!!!11!!1

2020-12-06 09:14 UTC, mrosminin reviewed
looks awesome

2020-12-07 23:51 UTC, DmitriyVTitov approved these changes
ОК

2020-12-08 11:24 UTC, merged