hw17
mrosminin/go-core pull request #28
Opened 2021-01-03 12:34 UTC by mrosminin

Создать проект со стандартной структурой каталогов, состоящий из единственного исполняемого пакета.  Этот пакет должен запускать веб-сервер, имеющий API из одного метода “/auth” принимающего JSON с учётными данными пользователя, проверяющего учётные данные, и возвращающего JWT-токен с правами пользователя. 

Пользователи с паролями и наборами прав должны храниться в массиве в службе.
Для метода аутентификации должен быть тест.

Используя пакет из состава Gorilla Toolkit добавить middleware для логирования доступа к службе в формате Apache Common Log Format.

2021-01-03 12:36 UTC, mrosminin reviewed
OK

2021-01-03 13:29 UTC, DmitriyVTitov requested changes

2021-01-03 13:29 UTC, DmitriyVTitov commented on homework-17/cmd/auth/main.go
> +	_ = api.New(r)
это что за конструкция?
если результат функции не интересен, то `... =` можно вообще опустить.

2021-01-03 13:29 UTC, DmitriyVTitov commented on homework-17/cmd/auth/main.go
> +}
```
api := api.New(r)
http.ListenAndServe(":8080", api.r)
```
хотя всё равно не очень.
```
api.Use(r)
http.ListenAndServe(":8080", r)
```
тоже так себе, конечно

2021-01-03 13:29 UTC, DmitriyVTitov commented on homework-17/pkg/api/api_test.go
> +	}
интересно: что же здесь было?

2021-01-03 13:29 UTC, DmitriyVTitov commented on homework-17/pkg/api/api.go
> +		http.Error(w, err.Error(), http.StatusUnauthorized)
добавь тест с неверным паролем. что тут получится?

2021-01-03 15:12 UTC, mrosminin commented on homework-17/pkg/api/api.go
> +		http.Error(w, err.Error(), http.StatusUnauthorized)
тяжело возвращаться к реальности)

2021-01-03 15:12 UTC, mrosminin reviewed
ОК

2021-01-04 16:03 UTC, DmitriyVTitov approved these changes
ОК

2021-01-04 16:03 UTC, DmitriyVTitov commented on homework-17/cmd/auth/main.go
> +	api := api.New(r)
и маршрутизатор можно создать в конструкторе API

2021-01-04 16:03 UTC, DmitriyVTitov commented on homework-17/pkg/api/api.go
> +	}
не факт, может просто пароль неверный

2021-01-04 16:03 UTC, DmitriyVTitov commented on homework-17/pkg/api/api.go
> +	}
и ошибки лучше с маленькой писать

2021-01-04 17:23 UTC, mrosminin commented on homework-17/cmd/auth/main.go
> +	api := api.New(r)
да не стоит, тогда роутер нужно экспортировать, т.к. ListenAndServer надо делать в вызывающем коде, т.к. в тестах свой ServeHTTP

2021-01-04 17:23 UTC, merged