homework-3
mrosminin/go-core pull request #4
Opened 2020-10-21 21:27 UTC by mrosminin

2020-10-23 18:59 UTC, DmitriyVTitov requested changes
Галиматья.

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +type myType string
отличное имя. надо бы лучше, да некуда

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +func Search(i Scanner, str string) (Pages, error) {
вот почему не `s Scanner`? вот даже интересно.

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +	data, err := i.Scan()
i.Phone(). вот это что ли, родное, хипстерское?

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +func (pp Pages) Find(s string) (Pages, error) {
и зачем функция возвращает ошибку? она же не может возникнуть!
на будущее задел?

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +		return nil, errors.New("ссылок не найдено")
а разве это ошибка? ну вернуть пустой результат и что?

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +	for _, s := range sites {
что такое sites?

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +		data, err := Search(s, *str)
функция Search первым аргументом принимает интерфейс. почему тут передаётся сайт?
не понимаю

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +type StubType int
надо больше type

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main_test.go
> +}
вот тут интерфейс применён верно

2020-10-23 18:59 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main_test.go
> +	st := new(StubType)
почему не `stub`. экономишь?

2020-10-24 20:34 UTC, mrosminin commented on homework-3/cmd/engine/main.go
> +		data, err := Search(s, *str)
я тоже не врублюсь. Она принимает первый аргументом - интерфейс, т.е. переменную типа данных, которая реализует интерфейс сканнер.
И если это заглушка, то туда передается переменная s := new(StubType), а если это реальные данные, с ними еще работать предстоит в ф-ии Search. Поэтому замечание не понял.

2020-10-26 10:49 UTC, closed without merging