homework 3
mrosminin/go-core pull request #5
Opened 2020-10-25 12:23 UTC by mrosminin

упрощенная версия

2020-10-25 12:24 UTC, mrosminin commented on homework-3/cmd/engine/main.go
> +		data, err := p.Scan()
вызывается метод типа Page

2020-10-25 12:24 UTC, mrosminin commented on homework-3/cmd/engine/main_test.go
> +	got, err := s.Scan()
вызывается метод типа StubType

2020-10-26 09:36 UTC, DmitriyVTitov requested changes
Помимо всяких небольших ошибок в дизайне кода, главное:
1. если объявлен интерфейс, то должен быть код (функция), использующий этот интерфейс (принимающая его как аргумент).
2. в рабочем коде в эту функцию передаётся одна реализация интерфейса (реальная), а в тестовом коде - другая (заглушка). тест, естественно, на ту самую функцию, принимающую аргументом интерфейс.

Примеры:
https://github.com/hardcode-dev/go-core/tree/master/3-syntax-two/interface3/cmd
https://github.com/hardcode-dev/go-core/tree/master/7-oop/ifaces

2020-10-26 09:36 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +}
1. где комментарий?
2. это что - документ? ОК.
3. почему документ имеет вложенный интерфейс поискового робота?

2020-10-26 09:36 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +}
почему у веб-страницы вдруг появился какой-то метод сканирования? что может сканировать веб-страница?

2020-10-26 09:36 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +}
строки были бы понятнее

2020-10-26 09:36 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +		data, err := p.Scan()
метод не может быть "типа Page". метод имеет ссылочный тип "функция" и аргумент-получатель некоторого типа данных.
говорят метод объекта Page - и это контринтуитивно, конечно, в смысле что страница имеет такие методы.

2020-10-26 09:36 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +type Page struct {
кстати, а зачем этот тип является экспортируемым?

2020-10-26 09:36 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +		for *str == "" {
какая-то дикая конструкция
тут должно быть что-то совершенно очевидное, а появляются какие-то трюки

2020-10-26 09:36 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main.go
> +}
вот объявлен интерфейс. где он используется?

2020-10-26 09:36 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main_test.go
> +	got, err := s.Scan()
ОК, но где используется интерфейс?
У тебя здесь написан тест для одной из функций пакета-заглушки. Какую бизнес-логику (часть рабочего кода) ты здесь тестируешь? Да никакую. Здесь зачем-то тестируется заглушка.

2020-10-26 19:02 UTC, DmitriyVTitov approved these changes
Принято. Хоть и коряво, но решено.

2020-10-26 19:02 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main_test.go
> +func (StubType) Scan(url string) (data map[string]string, err error) {
а чё тогда в возвращаемых значениях и аргументе не убрал имена переменных?

2020-10-26 19:02 UTC, DmitriyVTitov commented on homework-3/cmd/engine/main_test.go
> +func Test_Scanner(t *testing.T) {
почему `Test_Scanner`?
должно быть `TestFuncName`, т.е. `TestScanPages`

2020-10-28 14:32 UTC, merged