homework-4
mrosminin/go-core pull request #6
Opened 2020-10-25 18:49 UTC by mrosminin

не очень понял зачем в задании было сортировать слайс с документами, он изначально выходит отсортированным, и зачем бинарный поиск по нему, когда можно просто взять элемент по индексу, ну да ладно, сделано по заданию.

2020-10-27 09:36 UTC, DmitriyVTitov requested changes
Мне не нравится вот это безобразие со сканирующими сайты веб-страницами. Ну и другие мелкие правки.
В целом, решено, но, считаю, надо поправить код. Такой код я в рабочий проект не приму ни при каких условиях.

2020-10-27 09:36 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main.go
> +	s := new(Page)
почему "Page" становится "s".
да и вообще, почему функции сканирования сайтов нужно передать веб-документ, который и будет что-то сканировать.

2020-10-27 09:36 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main_test.go
> +func Test_Index(t *testing.T) {
что за Index?
нет такой функции

2020-10-27 09:36 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main_test.go
> +	err := ScanPages(s, []Page{{Url: "test1"}, {Url: "test2"}})
здесь не может быть ошибки в принципе
и два url зачем?

2020-10-27 09:36 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main_test.go
> +func Test_Index(t *testing.T) {
а, так это тест для пакета Index?
тогда что он делает в пакете Main?

2020-10-27 09:36 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +var Docs []Doc
глобальные переменные - не очень хорошо
вот эти вот Index и Docs неплохо было бы объединить в структуру и назвать её как-нибудь типа Service.
т.е. index.Service - служба индексирования. ну и конструктор нужен был бы, который бы возвращал указатель на службу.
посмотри как это сделано в нашем проекте, в любой службе

2020-10-27 09:36 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +func Fill(data map[string]string) {
и все эти функции должны бы быть методами
и потом ещё было бы возможно расцепить ядро и индекс с помощью интерфейса. при возникновении такой потребности.

2020-10-27 09:36 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +	}
это чё такое? должно быть полное совпадение с ключом.
зачем поиск по слогам?

2020-10-27 09:36 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +	for _, idx := range unique(resIdx) {
лучше при добавлении документов в индекс заботиться об уникальности ID, чем при каждом поиске!
ну обсуждали же вчера, ну что такое, ну как обычно, ну ни в коня...

2020-10-28 15:40 UTC, mrosminin reviewed
ОК

2020-10-28 22:27 UTC, DmitriyVTitov requested changes
Опять веб-страница сканирует Интернет. Опять одни и те же ошибки.
Плохо.

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main.go
> +}
я бы объявил этот тип в сканере - он там возникает по сути (я так и сделал в примере, который ты не посмотрел)

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main.go
> +}
я это не приму!
уже 10 раз написал!

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main.go
> +}
функция перегружена: она делает два абсолютно разных действия и требует две зависимости
как это тестировать?

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main.go
> +	i := index.New()
i - счётчик цикла

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main.go
> +		}
плохая, мутная конструкция

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main_test.go
> +func Test_Scanner(t *testing.T) {
имя теста строится так: `TestFunctionName` или `TestObject_MethodName` или `Test_functionName`

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main_test.go
> +	err := ScanPages(stub, i, []string{"http://..."})
[]string{"http://..."} - какая-то галиматья!

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main_test.go
> +		t.Errorf("Scan(): получили %d, должны были %d\n", len(got), want)
\n не нужно здесь

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +func (s *Service) Fill(data map[string]string) {
комментарии закончились?

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +		}
все ключи различны (так устроена хэш-таблица). зачем добавление при поиске равенства строк?

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +func unique(input []int) []int {
плохое имя. что уникально? не понятно.

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +	u := make([]int, 0, len(input))
ненужная конструкция

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/pkg/index/index_test.go
> +func Test_Find(t *testing.T) {
вот тест написан неплохо

2020-10-28 22:27 UTC, DmitriyVTitov commented on homework-4/pkg/stub/stub.go
> +}
и что это за код? где используется?

2020-10-30 11:45 UTC, mrosminin commented on homework-4/cmd/engine/main.go
> +		}
в чем мутность то? все - чЁтко

2020-10-30 19:19 UTC, DmitriyVTitov approved these changes
Более-менее. Скорее даже более.

2020-10-30 19:19 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main.go
> +func (e *Engine) Find(str string) []crawler.Document {
где пустая строка?

2020-10-30 19:19 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main.go
> +func (e *Engine) ScanPage(url string, depth int) error {
где комментарии?

2020-10-30 19:19 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main_test.go
> +func Test_Engine(t *testing.T) {
функции `Engine` у тебя нет.
я же подробно расписал как строится имя теста!

2020-10-30 19:19 UTC, DmitriyVTitov commented on homework-4/cmd/engine/main_test.go
> +			if got := e.Find(tt.s); len(got) != tt.want {
функция Find состоит из одной строки, т.е. ты тестируешь по сути функцию из пакета index.
тогда почему тест в другом пакете?

2020-10-30 19:19 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +}
интерфейс нигде не используется!
задел на будущее?

2020-10-30 19:19 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +	ids, ok := s.Index[strings.ToLower(str)]
43 засунуть в 44

2020-10-30 19:19 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +	ids, ok := s.Index[strings.ToLower(str)]
между if и !ok

2020-10-30 19:19 UTC, DmitriyVTitov commented on homework-4/pkg/index/index.go
> +}
эта функция сложная, выполняется сравнительно долго и требует памяти.
гораздо лучше было бы написать функцию, которая возвращала бы булево значение, означающее наличие элемента в массиве.

2020-10-30 19:19 UTC, DmitriyVTitov commented on homework-4/pkg/index/index_test.go
> +func Test_Find(t *testing.T) {
вот и зачем ты тестируешь этот же код выше?

2020-10-30 19:23 UTC, mrosminin commented on homework-4/pkg/index/index.go
> +}
ну типа того, в струтуре Engine есть поле типа Indexer. В него кладу экземпляр службы Index. А мог бы какой-нибудь заглушки.

2020-11-01 10:28 UTC, mrosminin commented on homework-4/cmd/engine/main_test.go
> +			if got := e.Find(tt.s); len(got) != tt.want {
здесь тестируются функции ScanPage и Find - оба метода Engine. Тест в main потому как,  Engine в отдельный пакет не вынесен.В рамках след задания вынесу.

2020-11-01 10:29 UTC, mrosminin commented on homework-4/pkg/index/index.go
> +	ids, ok := s.Index[strings.ToLower(str)]
ну а как засунусть, мне ids ниже нужны, а так переменная только в рамках if будет видима

2020-11-01 10:46 UTC, merged